# Generated by Django 6.0.7 on 2026-07-16 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=50)),
                ('version_tag', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('deployed_at', models.DateTimeField(auto_now_add=True)),
                ('rollback_notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SustainabilityMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('carbon_offset_mapping', models.FloatField(blank=True, help_text='Equivalent carbon offset value', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgentFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor', models.CharField(max_length=100)),
                ('rating', models.CharField(choices=[('thumbs_up', 'Thumbs Up'), ('thumbs_down', 'Thumbs Down')], max_length=20)),
                ('feedback_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='api.alert')),
            ],
        ),
        migrations.CreateModel(
            name='IncidentBiasAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demographic_flags', models.JSONField(blank=True, null=True)),
                ('location_data', models.CharField(max_length=100)),
                ('audit_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.incident')),
            ],
        ),
    ]
