# Generated by Django 5.2.5 on 2026-07-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_modelversion_sustainabilitymetric_agentfeedback_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(max_length=50, unique=True)),
                ('autonomy_level', models.CharField(default='advisory', max_length=20)),
                ('model_engine', models.CharField(default='gpt-4o-mini', max_length=50)),
                ('temperature', models.FloatField(default=0.2)),
                ('confidence_threshold', models.IntegerField(default=92)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='incidentbiasaudit',
            old_name='location_data',
            new_name='auditor',
        ),
        migrations.RemoveField(
            model_name='incidentbiasaudit',
            name='demographic_flags',
        ),
        migrations.AddField(
            model_name='incidentbiasaudit',
            name='is_biased',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='incidentbiasaudit',
            name='audit_notes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
